spring:
  profiles:
    default: local

  datasource:
    # Automatic Mixed mode
    # Reference: https://www.h2database.com/html/features.html#auto_mixed_mode
    url: jdbc:h2:~/cafe-kiosk;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: never
---
# Local Test 용 Profile
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # Hibernate 초기화 후 data.sql 실행
    # 개발용
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  #H2 console 접근 허용
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

