spring:
  profiles:
    default: local

  datasource:
    # Automatic Mixed mode
    # Reference: https://www.h2database.com/html/features.html#auto_mixed_mode
    url: jdbc:h2:~/cafe-kiosk;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: never
